import "./globals.css";
import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Tesseract Reports",
  description: "Cognitive & Architectural Compass for Codebases"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header className="border-b border-white/10">
          <div className="container py-4 flex items-center justify-between">
            <Link href="/" className="flex items-center gap-2 font-semibold tracking-wide">
              <Image
                src="/logo-tesseract.png"
                alt="Tesseract logo"
                width={28}
                height={28}
                className="rounded-sm"
                priority
              />
              <span>
                Tesseract <span className="text-ink-400">Reports</span>
              </span>
            </Link>
            <div className="text-sm text-ink-400">Auto-reading from /reports</div>
          </div>
        </header>
        <main className="container py-8">{children}</main>
        <footer className="container py-10 text-ink-500 text-sm">
          Built with ❤️ for clarity. Data from JSON reports generated by Tesseract.
        </footer>
      </body>
    </html>
  );
}
